#!/usr/bin/env python3
import sys
from pathlib import Path

def escape_c_string(s: str) -> str:
    # Escape backslashes and double quotes, and use \n for newlines
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n"\n"')

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print('Usage: embed_web.py input.html output.h')
        sys.exit(2)
    inp = Path(sys.argv[1])
    out = Path(sys.argv[2])
    html = inp.read_text(encoding='utf-8')
    esc = escape_c_string(html)
    header = f'''/* Generated by embed_web.py - DO NOT EDIT */
#ifndef WEB_INDEX_H
#define WEB_INDEX_H

#include <stddef.h>

const char index_html[] =
"{esc}";

const size_t index_html_len = sizeof(index_html) - 1;

#endif // WEB_INDEX_H
'''
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(header, encoding='utf-8')
    print('Wrote', out)
